/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_v002060_mjpegplayer_NativeOpenGLNV21Renderer */

#ifndef _Included_com_example_v002060_mjpegplayer_NativeOpenGLNV21Renderer
#define _Included_com_example_v002060_mjpegplayer_NativeOpenGLNV21Renderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_v002060_mjpegplayer_NativeOpenGLNV21Renderer
 * Method:    nativeOnSurfaceCreated
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_v002060_mjpegplayer_NativeOpenGLNV21Renderer_nativeOnSurfaceCreated
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_v002060_mjpegplayer_NativeOpenGLNV21Renderer
 * Method:    nativeOnSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_v002060_mjpegplayer_NativeOpenGLNV21Renderer_nativeOnSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_v002060_mjpegplayer_NativeOpenGLNV21Renderer
 * Method:    nativeOnDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_v002060_mjpegplayer_NativeOpenGLNV21Renderer_nativeOnDrawFrame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
