/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_v002060_mjpegplayer_MainActivity */

#ifndef _Included_com_example_v002060_mjpegplayer_MainActivity
#define _Included_com_example_v002060_mjpegplayer_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_v002060_mjpegplayer_MainActivity
 * Method:    testSurface
 * Signature: (Landroid/view/Surface;[B)V
 */
JNIEXPORT void JNICALL Java_com_example_v002060_mjpegplayer_MainActivity_testSurface
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     com_example_v002060_mjpegplayer_MainActivity
 * Method:    startPlay
 * Signature: (Landroid/view/Surface;[B)V
 */
JNIEXPORT void JNICALL Java_com_example_v002060_mjpegplayer_MainActivity_startPlay
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     com_example_v002060_mjpegplayer_MainActivity
 * Method:    startUvcPreview
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_example_v002060_mjpegplayer_MainActivity_startUvcPreview
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_example_v002060_mjpegplayer_MainActivity
 * Method:    stopUvcPreview
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_v002060_mjpegplayer_MainActivity_stopUvcPreview
  (JNIEnv *, jobject);

/*
 * Class:     com_example_v002060_mjpegplayer_MainActivity
 * Method:    startUvcDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_v002060_mjpegplayer_MainActivity_startUvcDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_example_v002060_mjpegplayer_MainActivity
 * Method:    stopUvcDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_v002060_mjpegplayer_MainActivity_stopUvcDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_example_v002060_mjpegplayer_MainActivity
 * Method:    getGlobalAddress
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_v002060_mjpegplayer_MainActivity_getGlobalAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_example_v002060_mjpegplayer_MainActivity
 * Method:    sendGlobalAdress
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_v002060_mjpegplayer_MainActivity_sendGlobalAdress
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
