/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_v002060_mjpegplayer_MainActivity */

#ifndef _Included_com_example_v002060_mjpegplayer_MainActivity
#define _Included_com_example_v002060_mjpegplayer_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_v002060_mjpegplayer_MainActivity
 * Method:    testSurface
 * Signature: (Landroid/view/Surface;[B)V
 */
JNIEXPORT void JNICALL Java_com_example_v002060_mjpegplayer_MainActivity_testSurface
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     com_example_v002060_mjpegplayer_MainActivity
 * Method:    startPlay
 * Signature: (Landroid/view/Surface;[B)V
 */
JNIEXPORT void JNICALL Java_com_example_v002060_mjpegplayer_MainActivity_startPlay
  (JNIEnv *, jobject, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
